var hoge01 = charIDToTypeID( "Mk  " );
var hoge02 = new ActionDescriptor();
var hoge03 = charIDToTypeID( "null" );
var hoge04 = new ActionReference();
var hoge05 = charIDToTypeID( "Dcmn" );
hoge04.putClass( hoge05 );
hoge02.putReference( hoge03, hoge04 );
var hoge06 = charIDToTypeID( "Usng" );
var hoge07 = new ActionReference();
var hoge08 = charIDToTypeID( "Lyr " );
var hoge09 = charIDToTypeID( "Ordn" );
var hoge10 = charIDToTypeID( "Trgt" );
hoge07.putEnumerated( hoge08, hoge09, hoge10 );
hoge02.putReference( hoge06, hoge07 );
executeAction( hoge01, hoge02, DialogModes.NO );
var hoge11 = stringIDToTypeID( "trim" );
var hoge12 = new ActionDescriptor();
var hoge13 = stringIDToTypeID( "trimBasedOn" );
var hoge14 = stringIDToTypeID( "trimBasedOn" );
var hoge15 = charIDToTypeID( "Trns" );
hoge12.putEnumerated( hoge13, hoge14, hoge15 );
var hoge16 = charIDToTypeID( "Top " );
hoge12.putBoolean( hoge16, true );
var hoge17 = charIDToTypeID( "Btom" );
hoge12.putBoolean( hoge17, true );
var hoge18 = charIDToTypeID( "Left" );
hoge12.putBoolean( hoge18, true );
var hoge19 = charIDToTypeID( "Rght" );
hoge12.putBoolean( hoge19, true );
executeAction( hoge11, hoge12, DialogModes.NO );